name: Android Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Give Gradlew permissions
        run: chmod +x gradlew

      - name: Clean project
        run: ./gradlew clean

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Run Android Instrumented Tests (API 34 - Android 14)
        uses: reactivecircus/android-emulator-runner@v2
        continue-on-error: true
        with:
          api-level: 34
          target: default
          arch: x86_64
          profile: Pixel_6_Pro
          emulator-options: -no-window -no-snapshot -noaudio -gpu swiftshader_indirect
          disable-animations: true
          script: |
            adb wait-for-device
            adb shell settings put global window_animation_scale 0
            adb shell settings put global transition_animation_scale 0
            adb shell settings put global animator_duration_scale 0
            sleep 90
            ./gradlew connectedDebugAndroidTest || echo "Android tests failed, continuing pipeline..."

      - name: Upload Android Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-report
          path: app/build/reports/androidTests/connected/
